<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array (
  'Companies' => 'Yritykset',
  'Cost-benefit calculations' => 'Liiketoimintalaskelmat',
  'Create a cost-benefit calculation' => 'Luo liiketoimintalaskelma',
  'Create a remark' => 'Luo huomio',
  'Create company' => 'Luo yritys',
  'Name' => 'Nimi',
  'Realized' => 'Toteutunut',
  'Update company' => 'Päivitä yritys',
  'Update the cost-benefit calculation' => 'Päivitä liiketoimintalaskelma',
  'Update the remark' => 'Päivitä huomio',
  'monthly' => 'kuukausittainen',
  'weekly' => 'viikottainen',
  'Company ID' => 'Yrityksen id',
  'Cost-benefit calculation' => 'Liiketoimintalaskelma',
  'Create Date' => 'Luontipäivä',
  'Description' => 'Kuvaus',
  'Email' => 'Sähköposti',
  'Event Date' => 'Tapahtumapäivä',
  'ID' => 'ID',
  'Login' => 'Kirjaudu',
  'Logout ({user})' => 'Kirjaudu ulos ({user})',
  'Password' => 'Salasana',
  'Remarks' => 'Huomiot',
  'Role' => 'Rooli',
  'Significance' => 'Merkitys',
  'Status' => 'Tila',
  'Token Customer ID' => 'Avainasiakkaan ID',
  'Username' => 'Käyttäjännimi',
  'Welcome' => 'Tervetuloa',
  'You are logged in as' => 'Olet kirjautuneena käyttäjänä',
);
