<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account Mail Sent' => '',
    'Backend User Created' => '',
    'Bank Account Created' => '',
    'ID' => '',
    'Industry ID' => '',
    'Openerp Database Created' => '',
    'Support company' => '',
    'Token Customer ID' => '',
    'Token Key ID' => '',
    'Have fun' => '@@Pidä hauskaa@@',
    'OpenERP account' => '@@OpenERP tunnus@@',
    'Active' => 'Aktiivinen',
    'Backend account' => 'Backend-tunnus',
    'Bank account' => 'Pankkitunnus',
    'Business ID' => 'Y-tunnus',
    'Company identifaction tag (short name)' => 'Yrityksen tunnus',
    'Company name' => 'Yrityksen nimi',
    'Create Time' => 'Luontiaika',
    'Email' => 'Sähköposti',
    'Employees' => 'Työntekijät',
    'Futurality account for' => 'Futurality-tunnukset yritykselle',
    'Futurality business simulation' => 'Futurality liiketoimintasimulaatioon',
    'Login from' => 'Kirjaudu täältä',
    'Odoo account' => 'Odoo-tunnus',
    'Password' => 'Salasana',
    'User account' => 'Käyttäjätunnus',
    'Welcome to Futurality' => 'Tervetuloa Futuralityyn',
    'You have created a company in the' => 'Olet luonut yrityksen',
    'Your company' => 'Yrityksesi',
];
