<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array (
  'Account Mail Sent' => '',
  'Active' => '',
  'Backend User Created' => '',
  'Bank Account Created' => '',
  'Business ID' => '',
  'Company identifaction tag (short name)' => '',
  'Company name' => '',
  'Create Time' => '',
  'Email' => 'Sähköposti',
  'Employees' => 'Työntekijät',
  'ID' => '',
  'Industry ID' => '',
  'Openerp Database Created' => '',
  'Token Customer ID' => '',
  'Token Key ID' => '',
  'Backend account' => 'Raportointitunnukset',
  'Bank account' => 'Pankkitunnus',
  'Futurality account for' => 'Futurality tunnukset yritykselle',
  'Futurality business simulation' => 'Futurality liiketoimintasimulaatioon',
  'Have fun' => 'Pidä hauskaa',
  'Login from' => 'Kirjaudu täältä',
  'OpenERP account' => 'OpenERP tunnus',
  'Password' => 'Salasana',
  'User Id' => 'Käyttäjä id',
  'User id' => 'Käyttäjä id',
  'Welcome to Futurality' => 'Tervetuloa Futuralityyn',
  'You have created a company in the' => 'Olet luonut yrityksen',
  'Your business id is' => 'Yrityksesi y-tunnus on',
  'Your company name is' => 'Yrityksesi nimi on',
  'Your company tag is' => 'Yrityksesi tunnus on',
);
