<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Companies putting effort to their actions get more. "More" sales mean both more orders, but also orders with higher value.' => 'Yritykset, jotka panostavat toimintaansa, saavat enemmän. "Enemmän" tarkoittaa sekä että tilausia tulee enemmän, että tilaukset ovat arvoltaan suurempia',
    'Each company will get sales whether they improve their company or not.' => 'Kaikki yritykset saavat tilauksia, kehittivät he yrityksen toimintaa tai ei.',
    'Expenses' => 'Kulut',
    'Find out what are the differences between the products you have and the list you\'ve marked you have' => 'Tutki mitä eroa on tuotteilla jotka on listattu, ja mitä yrityksellä todellisuudessa on',
    'Health' => 'Terveyskulut',
    'If the invoice is confirmed, you will need to reconcile the invoice and create a copy' => 'Jos lasku on hyväksytty, se pitää hyvittää ja tehdä laskusta kopio',
    'If the invoice isn\'t confirmed yet, you can just cancel it and create a new copy' => 'Jos laskua ei ole hyväksytty, sen voi poistaa ja tehdä siitä kopion',
    'Loans' => 'Lainat',
    'MTO' => 'MTO / TOT',
    'MTS' => 'MTS / VOT',
    'Make to Stock' => 'Make to Stock / Varastoon (ohjautuva) tuotanto',
    'Marketing' => 'Markkinointi',
    'PO' => 'PO / OT',
    'Paying your employees' => 'Palkkojen maksaminen',
    'Product pricing' => 'Tuotteiden hinnoittelu',
    'Purchase Order' => 'Purchase Order / Ostotilaus',
    'RFQ' => 'RFQ',
    'Remarks' => 'Huomiot',
    'Remitted too few products: Create a new PO with missing products and remit them' => 'Tuloutimme liian vähän tuotteita: Luo uusi ostotilaus puuttuvilla tuotteita ja tulouta ne',
    'Remitted too many products: Manually fix the product saldos' => 'Tuloutimme liian paljon tuotteita: Korjaa tuotesaldot manuaalisesti',
    'Request for Quotation' => 'Request for Quotation (tarjouspyyntö)',
    'Revenues' => 'Toimitilat',
    'SO' => 'SO / MT',
    'Sale Order' => 'Sale Order / Myyntitilaus',
    'The customer hasn\'t paid their invoice (correctly)' => 'Asiakas ei ole maksanut laskua (oikein)',
    'These will increase your sales' => 'Nämä lisäävät myyntiä',
    'We paid an invoice wrong / twice / etc.' => 'Maksoimme laskun väärin / kahdesti / tms.',
    'We remitted different products that we ordered' => 'Tuloutimme eri tuotteita kuin tilasimme',
    'What are the criteria used to decide the amount of our sales?' => 'Millä kriteereillä saamme myyntiä?',
    'What does this term mean?' => 'Mitä tämä termi tarkoittaa?',
    'a derivative from all the above' => 'johdannainen kaikista ylläolevista',
    'a health plan increases your employee effiency' => 'työterveys lisää työntekijöiden tuottavuutta',
    'ads, marketing campaigns, etc.' => 'mainokset, markkinointikampanjat, yms.',
    'be professional and friendly' => 'ole ammattimainen ja ystävällinen',
    'instructor can give notes about your company' => 'ohjaaja voi antaa huomioita yrityksestänne',
    'lower loan amount effects your sales slightly' => 'pienempi lainasumma vaikuttaa myyntiin hieman',
    'material etc. expenses effect your sales slightly' => 'materiaali, yms. -kulut vaikuttavat myyntiin hieman',
    'smart pricing gets more customers' => 'järkevä hinnoittelu lisää asiakkaita',
    'your company HQ location' => 'yrityksen päämajan sijainti',
    'your data and phone connections' => 'data- ja puhelinyhteydet',
    '(more) will result in higher employee satisfaction' => '(enemmän) lisää työntekijöiden tyytyväisyyttä',
    'Brand' => 'Brändi',
    'Communications' => 'Yhteydet',
    'Contact the customer and settle the matter with them' => 'Ota yhteyttä asiakkaaseen ja sovi asia',
    'Contact the supplier and settle the matter with them' => 'Ota yhteyttä toimittajaan ja sovi asia',
    'Customer support' => 'Asiakaspalvelu',
    'Make to Order' => 'Make to Order / Tilausohjautuva tuotanto',
];
