<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Modules' => 'Moduulit',
    'Admin actions' => 'Admin toiminnot',
    'Bank accounts' => 'Pankkitilit',
    'Companies' => 'Yritykset',
    'Keys' => 'Avaimet',
    'Users' => 'Käyttäjät',
    'Automated orders' => 'Automaattitilaukset',
    'Company' => 'Yritys',
    'Cost-benefit calculation' => 'Liiketoimintalaskelma',
    'Customer payments' => 'Asiakkaiden maksut',
    'Customers' => 'Asiakkaat',
    'Employees' => 'Työntekijät',
    'Info' => 'Info',
    'Invoices' => 'Laskut',
    'Orders' => 'Tilaukset',
    'Products' => 'Tuotteet',
    'Purchase orders' => 'Ostotilaukset',
    'Remarks' => 'Huomiot',
    'Sale orders' => 'Myyntitilaukset',
    'Suppliers' => 'Toimittajat',
    'Timecards' => 'Kellokortit',
    'Timesheets' => 'Tuntikirjaukset',
];
