<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array (
  'A short tag used for company prefix' => '',
  'Backend Password' => '',
  'Bank Password' => '',
  'Company ID' => '',
  'Contact email' => '',
  'Customer city' => '',
  'Hello, {username}!' => '',
  'Human readable name' => '',
  'ID' => '',
  'Openerp Password' => '',
  'Phone number' => '',
  'Postal Code' => '',
  'Street address' => '',
  'Unique ID
' => '',
  '0: student; 1: instructor; 2: manager; 3: admin' => '@@@@',
  'Email' => '@@@@',
  'Password' => '@@@@',
  'Status' => '@@@@',
  'Token Customer ID' => '@@@@',
  'Username' => '@@@@',
);
