<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'A short tag used for company prefix' => '',
    'Account' => '',
    'Active' => '',
    'Alter Date' => '',
    'Amount' => '',
    'Average Wage Rate' => '',
    'Backend Password' => '',
    'Bank Accounts' => '',
    'Bank Password' => '',
    'Bank Transaction ID' => '',
    'Communication' => '',
    'Company ID' => '',
    'Contact email' => '',
    'Costbenefit Calculation ID' => '',
    'Create Date' => '',
    'Create Demo Data' => '',
    'Create Init Data' => '',
    'Create Purchasing Orders' => '',
    'Create Time' => '',
    'Create {modelClass}' => '',
    'Created' => '',
    'Created by' => '',
    'Created on' => '',
    'Customer city' => '',
    'Description' => '',
    'Email' => '',
    'Employees' => '',
    'Event Time' => '',
    'Executed' => '',
    'Expiration Date' => '',
    'Human readable name' => '',
    'ID' => '',
    'Industries' => '',
    'Industry ID' => '',
    'Info' => '',
    'It is recommended you use an upgraded browser to display the {type} control properly.' => '',
    'Last Updated by' => '',
    'Last Updated on' => '',
    'Lifetime' => '',
    'Maximum Wage Rate' => '',
    'Minimum Wage Rate' => '',
    'Model' => '',
    'Name' => '',
    'Openerp Password' => '',
    'Openerp Purchase Order ID' => '',
    'Order' => '',
    'Order Automation ID' => '',
    'Order Setup ID' => '',
    'Organization' => '',
    'Phone number' => '',
    'Position' => '',
    'Postal Code' => '',
    'Reclaim Date' => '',
    'Rents' => '',
    'Rows' => '',
    'Sent' => '',
    'State' => '',
    'Street address' => '',
    'Token Customer ID' => '',
    'Token Key' => '',
    'Token Setup ID' => '',
    'Turnover' => '',
    'Type' => '',
    'Unique ID
' => '',
    'Value' => '',
    'Week' => '',
    'Weight' => '',
    'Year' => '',
    '0: student; 1: instructor; 2: manager; 3: admin' => '@@@@',
    'Clear field' => '@@@@',
    'Costbenefit Item Type ID' => '@@@@',
    'Hello, {username}!' => '@@@@',
    'Password' => '@@@@',
    'Phone' => '@@@@',
    'Select date & time' => '@@@@',
    'Status' => '@@@@',
    'Transactions' => '@@@@',
    'Username' => '@@@@',
];
