<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array (
  'Companies' => '',
  'Company ID' => '',
  'Cost-benefit calculation' => '',
  'Cost-benefit calculations' => '',
  'Create Date' => '',
  'Create a cost-benefit calculation' => '',
  'Create a remark' => '',
  'Create company' => '',
  'Description' => '',
  'Email' => '',
  'Event Date' => '',
  'ID' => '',
  'Login' => '',
  'Logout ({user})' => '',
  'Name' => '',
  'Password' => '',
  'Realized' => '',
  'Remarks' => '',
  'Role' => '',
  'Significance' => '',
  'Status' => '',
  'Token Customer ID' => '',
  'Update company' => '',
  'Update the cost-benefit calculation' => '',
  'Update the remark' => '',
  'Username' => '',
  'Welcome' => '',
  'You are logged in as' => '',
  'monthly' => '',
  'weekly' => '',
  'Company info' => '@@@@',
);
