<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account Mail Sent' => '',
    'Active' => '',
    'Backend User Created' => '',
    'Backend account' => '',
    'Bank Account Created' => '',
    'Bank account' => '',
    'Business ID' => '',
    'Company identifaction tag (short name)' => '',
    'Company name' => '',
    'Create Time' => '',
    'Email' => '',
    'Employees' => '',
    'Futurality account for' => '',
    'Futurality business simulation' => '',
    'ID' => '',
    'Industry ID' => '',
    'Login from' => '',
    'Odoo account' => '',
    'Openerp Database Created' => '',
    'Password' => '',
    'Support company' => '',
    'Token Customer ID' => '',
    'Token Key ID' => '',
    'User account' => '',
    'Welcome to Futurality' => '',
    'You have created a company in the' => '',
    'Your company' => '',
    'Have fun' => '@@@@',
    'OpenERP account' => '@@@@',
    'User Id' => '@@@@',
    'User id' => '@@@@',
    'Your business id is' => '@@@@',
    'Your company name is' => '@@@@',
    'Your company tag is' => '@@@@',
];
