<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '(more) will result in higher employee satisfaction' => '',
    'Brand' => '',
    'Communications' => '',
    'Companies putting effort to their actions get more. "More" sales mean both more orders, but also orders with higher value.' => '',
    'Contact the customer and settle the matter with them' => '',
    'Contact the supplier and settle the matter with them' => '',
    'Customer support' => '',
    'Each company will get sales whether they improve their company or not.' => '',
    'Expenses' => '',
    'Find out what are the differences between the products you have and the list you\'ve marked you have' => '',
    'Health' => '',
    'If the invoice is confirmed, you will need to reconcile the invoice and create a copy' => '',
    'If the invoice isn\'t confirmed yet, you can just cancel it and create a new copy' => '',
    'Loans' => '',
    'MTO' => '',
    'MTS' => '',
    'Make to Order' => '',
    'Make to Stock' => '',
    'Marketing' => '',
    'PO' => '',
    'Paying your employees' => '',
    'Product pricing' => '',
    'Purchase Order' => '',
    'RFQ' => '',
    'Remarks' => '',
    'Remitted too few products: Create a new PO with missing products and remit them' => '',
    'Remitted too many products: Manually fix the product saldos' => '',
    'Request for Quotation' => '',
    'Revenues' => '',
    'SO' => '',
    'Sale Order' => '',
    'The customer hasn\'t paid their invoice (correctly)' => '',
    'These will increase your sales' => '',
    'We paid an invoice wrong / twice / etc.' => '',
    'We remitted different products that we ordered' => '',
    'What are the criteria used to decide the amount of our sales?' => '',
    'What does this term mean?' => '',
    'a derivative from all the above' => '',
    'a health plan increases your employee effiency' => '',
    'ads, marketing campaigns etc.' => '',
    'be professional and friendly' => '',
    'instructor can give notes about your company' => '',
    'lower loan amount effects your sales slightly' => '',
    'material etc. expenses effect your sales slightly' => '',
    'smart pricing gets more customers' => '',
    'your company HQ location' => '',
    'your data and phone connections' => '',
    'Companies putting effort to their actions get more. "More" sales mean both
                more orders, but also orders with higher value.' => '@@@@',
    'Each company will get sales whether they improve their company or not.
                Companies putting effort to their actions get more. "More" sales mean both
                more orders, but also orders with higher value.' => '@@@@',
];
